// Generated by CoffeeScript 1.6.2
(function() {
  var flatstack, type;

  flatstack = require("flatstack");

  type = require("type-component");

  module.exports = {
    options: function() {
      return true;
    },
    decorate: function(target) {
      target.callstack = flatstack();
      return target.call = function(startEvent, endEvent, next) {
        var endState, startState,
          _this = this;

        if (type(next) !== "function") {
          next = function() {};
        }
        startState = "states." + startEvent;
        endState = "states." + endEvent;
        return this.callstack.push(function() {
          var error;

          error = void 0;
          _this.callstack.error(function(err) {
            return error = err;
          });
          _this.emit(startEvent);
          _this.set(startState, true);
          return _this.callstack.push(function() {
            _this.emit(endEvent);
            _this.set(endState, true);
            return next(error);
          });
        });
      };
    }
  };

}).call(this);
